version: '3.8'

services:
  node-app:
    image: node:14
    volumes:
      - ./frontend/bonfire:/app
    environment:
      - GH_TOKEN=token
    ports:
      - "3000:3000"
    command: /bin/bash -c "git clone https://username:token@github.com/username/Bonfire.git && cd Bonfire/frontend/bonfire && npm install && npm run build"
